In [1]:
from itertools import permutations, product
from math import factorial

### Задача 1.38
> Пятитомное собрание сочинений расположено на полке в случайном порядке. Какова вероятность того, что книги стоят слева направо в порядке нумерации томов (от 1 до 5)?

Рассмотрим событие $A$ — книги стоят в порядке $1,2,3,4,5$.

Всего существует

$P_5 = 5!$

перестановок пяти томов. Благоприятный вариант только один, поэтому

$P(A)=\frac{1}{5!}=\frac{1}{120}\approx0.00833$.

In [2]:
orders = list(permutations(range(1, 6)))
favorable = [order for order in orders if order == (1, 2, 3, 4, 5)]

p = len(favorable) / len(orders)

print(f'Всего перестановок: {len(orders)}')
print(f'Благоприятных: {len(favorable)}')
print(f'P(A) = {p:.5f}')

Всего перестановок: 120
Благоприятных: 1
P(A) = 0.00833


### Задача 1.43
> Наудачу взятый телефонный номер состоит из 5 цифр. Какова вероятность того, что в нем все цифры: а) различные; б) одинаковые; в) нечетные? Известно, что номер телефона не начинается с цифры ноль.

Всего допустимых пятизначных телефонных номеров:

$n=9\cdot10^4=90000$.

**а)** Все цифры различные. Для первой цифры — 9 вариантов, далее соответственно 9, 8, 7 и 6 вариантов:

$m_a=9\cdot9\cdot8\cdot7\cdot6=27216$,

$P(A)=\frac{27216}{90000}=0.3024$.

**б)** Все цифры одинаковые. Подходят номера $11111,22222,\ldots,99999$:

$m_b=9$,

$P(B)=\frac{9}{90000}=0.0001$.

**в)** Все цифры нечетные. Для каждой позиции возможны цифры $1,3,5,7,9$:

$m_c=5^5=3125$,

$P(C)=\frac{3125}{90000}=\frac{5}{144}\approx0.0347$.

In [3]:
digits = '0123456789'
first_digits = '123456789'

numbers = [
    (first,) + rest
    for first in first_digits
    for rest in product(digits, repeat=4)
]

total = len(numbers)

different = sum(len(set(number)) == 5 for number in numbers)
same = sum(len(set(number)) == 1 for number in numbers)
odd = sum(all(int(digit) % 2 == 1 for digit in number) for number in numbers)

print(f'Всего допустимых номеров: {total}')
print(f'а) Все цифры различные: {different} случаев, P = {different / total:.4f}')
print(f'б) Все цифры одинаковые: {same} случаев, P = {same / total:.4f}')
print(f'в) Все цифры нечетные: {odd} случаев, P = {odd / total:.4f}')

Всего допустимых номеров: 90000
а) Все цифры различные: 27216 случаев, P = 0.3024
б) Все цифры одинаковые: 9 случаев, P = 0.0001
в) Все цифры нечетные: 3125 случаев, P = 0.0347


> **Примечание.** В ответах к учебнику Кремера для пункта 1.43(а) напечатано значение $\frac{1}{27216}$. Оно не соответствует условию задачи: прямой перебор и классическое определение дают $\frac{27216}{90000}=0.3024$.

### Задача 1.48
> В старинной игре в кости необходимо было для выигрыша получить при бросании трех игральных костей сумму очков, превосходящую 10. Найти вероятности: а) выпадения 11 очков; б) выигрыша.

При бросании трех игральных костей имеется

$n=6^3=216$

равновозможных упорядоченных исходов.

**а)** Сумма очков равна 11. Программно переберем все исходы и посчитаем подходящие.

**б)** Для выигрыша сумма должна быть больше 10. Аналогично подсчитаем число исходов с суммой от 11 до 18.

In [4]:
outcomes = list(product(range(1, 7), repeat=3))
total = len(outcomes)

sum_11 = [outcome for outcome in outcomes if sum(outcome) == 11]
win = [outcome for outcome in outcomes if sum(outcome) > 10]

print(f'Всего исходов: {total}')
print(f'а) Сумма 11: {len(sum_11)} случаев, P = {len(sum_11) / total:.3f}')
print(f'б) Сумма больше 10: {len(win)} случаев, P = {len(win) / total:.3f}')

Всего исходов: 216
а) Сумма 11: 27 случаев, P = 0.125
б) Сумма больше 10: 108 случаев, P = 0.500
